name: Node Continuous Integration

on:
  pull_request:
    branches: [main , develop]
# env:
#   AWS_CHECK: ${{ secrets.AWS_CHECK}}
#   AWS_JOB: ${{ secrets.AWS_JOB }}

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    env: 
      STAGE: ${{ github.ref == 'refs/heads/main' && secrets.AWS_CHECK || secrets.AWS_JOB }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Print AWS_CHECK secret
        run: | 
          echo $STAGE
           
